apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldata
spec:
  selector:
    matchLabels:
      app: sqldata
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sqldata
    spec:
      containers:
      - name: sqldata
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "My!P@ssw0rd1"
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: sql-data
      volumes:
      - name: sql-data
        persistentVolumeClaim:
          claimName: sql-data

---
apiVersion: v1
kind: Service
metadata:
  name: sqldata
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqldata
